glib2: fix build when res_nquery is not available
Upstream commit "gio: Port GThreadedResolver to use res_nquery() to fix
thread-safety" introduced a bug that causes compile failures on
platforms where res_nquery is unavailable. This patch fixes that.

Bug 794606 has been opened upstream: https://bugzilla.gnome.org/show_bug.cgi?id=794606

On the OpenWrt buildbots this bug is visible during the arc_archs
compile:

  gthreadedresolver.c: In function 'do_lookup_records':
  gthreadedresolver.c:875:16: error: 'res' undeclared (first use in this function); did you mean '_res'?
     res_nclose (&res);
                  ^~~
                  _res
  gthreadedresolver.c:875:16: note: each undeclared identifier is reported only once for each function it appears in
  Makefile:3334: recipe for target 'libgio_2_0_la-gthreadedresolver.lo' failed
  make[8]: *** [libgio_2_0_la-gthreadedresolver.lo] Error 1

Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>